# Generated by Django 3.2.7 on 2021-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik_sources_ldap', '0012_auto_20210812_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsource',
            name='group_membership_attribute_uniqueness',
            field=models.BooleanField(default=False, help_text='Use object uniqueness field to map users to groups instead of using the distinguished name.', null=True),
        ),
    ]
